#{{#use_code_generation}}x#
targets:
  $default:
    builders:
      #{{#use_dart_mappable}}x#
      dart_mappable_builder:
        generate_for:
          - lib/src/types/optional.dart
        options:
          generateMethods:
            - stringify
      #x{{/use_dart_mappable}}x#
      #x{{#use_freezed}}x#
      freezed:
        generate_for:
          - lib/src/types/optional.dart
        options:
          copy_with: false
          map: false
          when: false
      #x{{/use_freezed}}x#
#{{/use_code_generation}}#
