version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - ci
  - package-ecosystem: pub
    directory: /
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - build
      - chore

  # Bricks
  - package-ecosystem: pub
    directory: /bricks/altoke_app/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - build
      - chore
      - b:altoke-app
      - s:scope
  - package-ecosystem: pub
    directory: /bricks/altoke_app/brick/hooks/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - build
      - b:altoke-app
      - s:hooks
  - package-ecosystem: pub
    directory: /bricks/altoke_app/e2e/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - build
      - test
      - b:altoke-app
      - s:e2e
  - package-ecosystem: pub
    directory: /bricks/altoke_app/reference/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - build
      - feat
      - b:altoke-app
      - s:reference
  - package-ecosystem: pub
    directory: /bricks/altoke_app/reference/packages/app/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - build
      - feat
      - b:altoke-app
      - s:reference
  - package-ecosystem: pub
    directory: /bricks/altoke_common/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - build
      - chore
      - b:altoke-common
      - s:scope
  - package-ecosystem: pub
    directory: /bricks/altoke_common/brick/hooks/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - build
      - b:altoke-common
      - s:hooks
  - package-ecosystem: pub
    directory: /bricks/altoke_common/e2e/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - build
      - test
      - b:altoke-common
      - s:e2e
  - package-ecosystem: pub
    directory: /bricks/altoke_common/reference/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - build
      - feat
      - b:altoke-common
      - s:reference
  - package-ecosystem: pub
    directory: /bricks/altoke_dart_package/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - build
      - chore
      - b:altoke-dart-pkg
      - s:scope
  - package-ecosystem: pub
    directory: /bricks/altoke_dart_package/brick/hooks/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - build
      - b:altoke-dart-pkg
      - s:hooks
  - package-ecosystem: pub
    directory: /bricks/altoke_dart_package/e2e/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - build
      - test
      - b:altoke-dart-pkg
      - s:e2e
  - package-ecosystem: pub
    directory: /bricks/altoke_dart_package/reference/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - build
      - feat
      - b:altoke-dart-pkg
      - s:reference
  - package-ecosystem: pub
    directory: /bricks/altoke_entity/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - build
      - chore
      - b:altoke-entity
      - s:scope
  - package-ecosystem: pub
    directory: /bricks/altoke_entity/brick/hooks/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - build
      - b:altoke-entity
      - s:hooks
  - package-ecosystem: pub
    directory: /bricks/altoke_entity/e2e/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - build
      - test
      - b:altoke-entity
      - s:e2e
  - package-ecosystem: pub
    directory: /bricks/altoke_entity/reference/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - build
      - feat
      - b:altoke-entity
      - s:reference
  - package-ecosystem: pub
    directory: /bricks/altoke_reactive_caches/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - build
      - chore
      - b:altoke-reactive-caches
      - s:scope
  - package-ecosystem: pub
    directory: /bricks/altoke_reactive_caches/brick/hooks/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - build
      - b:altoke-reactive-caches
      - s:hooks
  - package-ecosystem: pub
    directory: /bricks/altoke_reactive_caches/e2e/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - build
      - test
      - b:altoke-reactive-caches
      - s:e2e
  - package-ecosystem: pub
    directory: /bricks/altoke_reactive_caches/reference/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - build
      - feat
      - b:altoke-reactive-caches
      - s:reference

  # Tools
  - package-ecosystem: pub
    directory: /tools/brick_generator/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - build
      - t:brick-gen
  - package-ecosystem: pub
    directory: /tools/monorepo_elements/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - build
      - t:monorepo-elements
  - package-ecosystem: pub
    directory: /tools/pubspec_deps_sorter/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - build
      - t:pubspec-sorter
  - package-ecosystem: pub
    directory: /tools/readmes_resolver/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - build
      - t:readmes-resolver
  - package-ecosystem: pub
    directory: /tools/shell/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - build
      - t:shell
