b:app:
  - changed-files:
    - any-glob-to-any-file:
      - bricks/altoke_app/**
      - bricks/app/**

b:common:
  - changed-files:
    - any-glob-to-any-file:
      - bricks/altoke_common/**
      - bricks/common/**

b:dart_package:
  - changed-files:
    - any-glob-to-any-file:
      - bricks/altoke_dart_package/**
      - bricks/dart_package/**

b:entities:
  - changed-files:
    - any-glob-to-any-file:
      - bricks/altoke_entities/**
      - bricks/entities/**

b:entity:
  - changed-files:
    - any-glob-to-any-file:
      - bricks/altoke_entity/**
      - bricks/entity/**

b:local_database:
  - changed-files:
    - any-glob-to-any-file:
      - bricks/altoke_local_database/**
      - bricks/local_database/**

b:reactive_caches:
  - changed-files:
    - any-glob-to-any-file:
      - bricks/altoke_reactive_caches/**
      - bricks/reactive_caches/**

t:brick_generator:
  - changed-files:
    - any-glob-to-any-file:
      - tools/brick_generator/**

t:data_persistence_approach:
  - changed-files:
    - any-glob-to-any-file:
      - tools/data_persistence_approach/**

t:local_brick_installer:
  - changed-files:
    - any-glob-to-any-file:
      - tools/local_brick_installer/**

t:local_database_alternative:
  - changed-files:
    - any-glob-to-any-file:
      - tools/local_database_alternative/**

t:monorepo_elements:
  - changed-files:
    - any-glob-to-any-file:
      - tools/monorepo_elements/**

t:pubspec_deps_sorter:
  - changed-files:
    - any-glob-to-any-file:
      - tools/pubspec_deps_sorter/**

t:readmes_resolver:
  - changed-files:
    - any-glob-to-any-file:
      - tools/readmes_resolver/**

t:router_package:
  - changed-files:
    - any-glob-to-any-file:
      - tools/router_package/**

t:shell:
  - changed-files:
    - any-glob-to-any-file:
      - tools/shell/**

t:value_equality_approach:
  - changed-files:
    - any-glob-to-any-file:
      - tools/value_equality_approach/**

s:brick:
  - changed-files:
    - any-glob-to-any-file:
      - bricks/*/brick/*

s:hooks:
  - changed-files:
    - any-glob-to-any-file:
      - bricks/*/brick/hooks/**

s:e2e:
  - changed-files:
    - any-glob-to-any-file:
      - bricks/*/e2e/**

s:reference:
  - changed-files:
    - any-glob-to-any-file:
      - bricks/*/reference/**

s:scope:
  - changed-files:
    - any-glob-to-any-file:
      - bricks/*/*

s:template:
  - changed-files:
    - any-glob-to-any-file:
      - bricks/*/brick/__brick__/**

bot:
  - head-branch:
    - chore/.+/update-template
    - dependabot
    - docs/update-root-readme
    - docs/.+/update-readme

build:
  - head-branch:
    - dependabot/pub/.+

ci:
  - changed-files:
    - any-glob-to-any-file:
      - .github/**

docs:
  - changed-files:
    - any-glob-to-any-file:
      - '**/CHANGELOG.md'
      - '**/README.md'

test:
  - changed-files:
    - any-glob-to-any-file:
      - '**/test/**'
      - '**/e2e/**'
      - '**/*_test.dart'
