include: package:very_good_analysis/analysis_options.yaml
#{{#use_code_generation}}x#
analyzer:
  exclude:
    #{{#use_dart_mappable}}x#
    - lib/**.mapper.dart
    #x{{/use_dart_mappable}}x#
    #x{{#use_freezed}}x#
    - lib/**.freezed.dart
    #x{{/use_freezed}}#
#{{/use_code_generation}}x#
linter:
  rules:
    # HACK: Disable conflicting rule
    # Issue: https://github.com/dart-lang/dart_style/issues/1646
    require_trailing_commas: false
