name: altoke_entity
description: Representation of different altoke entity variants.
version: 0.0.1+1
publish_to: none
#remove-start#
resolution: workspace
#remove-end#
#w 2v w#

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  altoke_common:
    #w 1v 4> w#
    #replace-start#
    path: ../../../altoke_common/reference/common/
    #with#
    # path: ../common/
    #replace-end#
  #w 1v 2> w#
  #{{#use_dart_mappable}}#
  dart_mappable: ^4.4.0
  #{{/use_dart_mappable}}#
  #{{#use_equatable}}#
  equatable: ^2.0.7
  #{{/use_equatable}}#
  #{{#use_freezed}}#
  freezed_annotation: ^2.4.4
  #{{/use_freezed}}#
  #{{#use_overrides}}
  meta: ^1.15.0
  #{{/use_overrides}}#
#w 2v w#

dev_dependencies:
  #{{#use_code_generation}}#
  #w 1v 2> w#
  build_runner: ^2.4.15
  #w 1v 2> w#
  #{{/use_code_generation}}#
  #{{#use_dart_mappable}}#
  dart_mappable_builder: ^4.3.0
  #{{/use_dart_mappable}}#
  #{{#use_freezed}}#
  freezed: ^2.5.7
  #{{/use_freezed}}#
  #w 1v 2> w#
  test: ^1.25.8
  very_good_analysis: ^7.0.0
