name: {{project_name.snakeCase()}}
description: An {{project_name.titleCase()}}.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.1 <4.0.0"

dependencies:
  {{#use_auto_route}}auto_route: ^9.2.2
  {{/use_auto_route}}flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  {{#use_go_router}}go_router: ^14.6.2
  {{/use_go_router}}intl: ^0.19.0
  riverpod_annotation: ^2.6.1

dev_dependencies:
  {{#use_auto_route}}auto_route_generator: ^9.0.0
  {{/use_auto_route}}build_runner: ^2.4.14
  custom_lint: ^0.7.0
  flutter_test:
    sdk: flutter
  {{#use_go_router}}go_router_builder: ^2.7.1
  {{/use_go_router}}meta: ^1.15.0
  mocktail: ^1.0.4
  path: ^1.9.0
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3
  very_good_analysis: ^7.0.0

flutter:
  generate: true
  uses-material-design: true
