name: altoke_app
description: An Altoke App.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.5.1 <4.0.0"
  flutter: ">=3.24.1 <4.0.0"

dependencies:
  #*w 1v 2> w*#
  #{{#use_auto_route}}#
  auto_route: ^9.2.2
  #*w 1v 2> w*#
  #{{/use_auto_route}}#
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  #*w 1v 2> w*#
  #{{#use_go_router}}#
  go_router: ^14.2.7
  #*w 1v 2> w*#
  #{{/use_go_router}}#
  intl: ^0.19.0
  riverpod_annotation: ^2.3.5

dev_dependencies:
  #*w 1v 2> w*#
  #{{#use_auto_route}}#
  auto_route_generator: ^9.0.0
  #*w 1v 2> w*#
  #{{/use_auto_route}}#
  build_runner: ^2.4.12
  custom_lint: ^0.6.5
  flutter_test:
    sdk: flutter
  #*w 1v 2> w*#
  #{{#use_go_router}}#
  go_router_builder: ^2.7.1
  #*w 1v 2> w*#
  #{{/use_go_router}}#
  meta: ^1.15.0
  mocktail: ^1.0.4
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13
  very_good_analysis: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
