include: package:very_good_analysis/analysis_options.yaml
analyzer:
  exclude:
    - lib/**.g.dart{{#use_auto_route}}
    - lib/**.gr.dart{{/use_auto_route}}
  plugins:
    - custom_lint
linter:
  rules:
    public_member_api_docs: false
    # HACK: Disable conflicting rule
    # Issue: https://github.com/dart-lang/dart_style/issues/1646
    require_trailing_commas: false
