include: package:very_good_analysis/analysis_options.yaml
analyzer:
  exclude:
    - lib/**.g.dart{{#use_auto_route}}
    - lib/**.gr.dart{{/use_auto_route}}
  plugins:
    - riverpod_lint
linter:
  rules:
    public_member_api_docs: false
plugins:
  riverpod_lint: ^3.1.0
