targets:
  $default:
    builders:
      {{#use_auto_route}}auto_route_generator:auto_route_generator:
        options:
          enable_cached_builds: true
        generate_for:
          - lib/routing/routes/**
      auto_route_generator:auto_router_generator:
        options:
          enable_cached_builds: true
        generate_for:
          - lib/routing/router.dart{{/use_auto_route}}{{#use_go_router}}go_router_builder:
        generate_for:
          - lib/routing/router.dart{{/use_go_router}}
      {{#use_riverpod}}riverpod_generator:
        options:
          provider_name_suffix: Pod
          provider_family_name_suffix: Pod
        generate_for:
          - lib/**/**_pod.dart
          - lib/**/**_pods.dart
          - lib/**/pod.dart
          - lib/**/pods.dart
          - lib/routing/router.dart{{/use_riverpod}}
