name: reactive_caches
description: In-memory reactive caches.
version: 0.0.1+1
publish_to: none

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  common:
    path: ../common/
  collection: ^1.18.0
  meta: ^1.11.0

dev_dependencies:
  test: ^1.25.2
  very_good_analysis: ^6.0.0
