name: isar_local_database
description: A persistent local database built on top of Isar.
version: 0.0.1+1
publish_to: none

environment:
  sdk: ">=3.5.1 <4.0.0"

dependencies:
  #*w 1v 2> w*#
  #*replace-start*#
  altoke_common:
    path: ../../../altoke_common/reference/
  #*with i2*#
  # common:
  #   path: ../../common/
  #*replace-end*#
  #*w 1v 2> w*#
  collection: ^1.19.0
  isar:
    hosted: https://pub.isar-community.dev/
    version: 3.1.8
  local_database:
    path: ../local_database/
  meta: ^1.15.0

dev_dependencies:
  build_runner: ^2.4.12
  isar_generator:
    hosted: https://pub.isar-community.dev/
    version: 3.1.8
  test: ^1.25.8
  very_good_analysis: ^6.0.0
