name: {{#use_sembast}}sembast_local_database{{/use_sembast}}
description: A persistent local database built on top of Sembast.
version: 0.0.1+1
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  common:
    path: ../../common/
  collection: ^1.19.0
  {{#preconditions_met}}local_database{{/preconditions_met}}:
    path: ../{{#preconditions_met}}local_database{{/preconditions_met}}/
  meta: ^1.15.0
  sembast: ^3.8.0+1

dev_dependencies:
  test: ^1.25.14
  very_good_analysis: ^7.0.0
