name: pubspec_deps_sorter
description: A tool to sort dependencies in pubspec.yaml files.
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  path: ^1.9.1

dev_dependencies:
  very_good_analysis: ^7.0.0
