name: pubspec_deps_sorter
description: A tool to sort dependencies in pubspec.yaml files.
publish_to: none

environment:
  sdk: ">=3.5.1 <4.0.0"

dependencies:
  path: ^1.9.0

dev_dependencies:
  very_good_analysis: ^7.0.0
