name: {{#requirements_met}}{{entity_singular.snakeCase()}}{{/requirements_met}}
description: {{package_description}}
version: 0.0.1+1
publish_to: none

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  common:
    path: ../common/
  {{#use_dart_mappable}}dart_mappable: ^4.5.0{{/use_dart_mappable}}{{#use_equatable}}equatable: ^2.0.7{{/use_equatable}}{{#use_freezed}}freezed_annotation: ^3.0.0{{/use_freezed}}{{#use_overrides}}meta: ^1.16.0{{/use_overrides}}

dev_dependencies:{{#use_code_generation}}
  build_runner: ^2.4.15
  {{/use_code_generation}}
  {{#use_dart_mappable}}dart_mappable_builder: ^4.5.0{{/use_dart_mappable}}{{#use_freezed}}freezed: ^3.0.4{{/use_freezed}}
  test: ^1.25.15
  very_good_analysis: ^7.0.0
