name: router_package
description: Router package.
version: 0.0.1+1
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  mason: ^0.1.0

dev_dependencies:
  very_good_analysis: ^7.0.0
