name: router_package
description: Router package.
version: 0.0.1+1
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  mason: ^0.1.1

dev_dependencies:
  very_good_analysis: ^9.0.0
