#{{#use_code_generation}}#
targets:
  $default:
    builders:
      #*w 1v 6> w*#
      #{{#use_dart_mappable}}#
      dart_mappable_builder:
        generate_for:
          - lib/src/types/_cf___use_dart_mappable___optional.dart
        options:
          generateMethods:
            - stringify
      #{{/use_dart_mappable}}#
      #{{#use_freezed}}#
      freezed:
        generate_for:
          - lib/src/types/_cf___use_freezed___optional.dart
        options:
          copy_with: false
          map: false
          when: false
      #{{/use_freezed}}#
#{{/use_code_generation}}#
#*w 1v w*#
