include: package:very_good_analysis/analysis_options.yaml
analyzer:
  exclude:
    - lib/**.g.dart
    #x{{#use_auto_route}}#
    - lib/**.gr.dart
    #x{{/use_auto_route}}#
  plugins:
    - custom_lint
linter:
  rules:
    public_member_api_docs: false
