name: altoke_reactive_caches_brick_hooks
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  mason: ^0.1.0
  path: ^1.9.0
  pubspec_deps_sorter:
    path: ../../../../tools/pubspec_deps_sorter
  pubspec_parse: ^1.4.0
  shell:
    path: ../../../../tools/shell

dev_dependencies:
  very_good_analysis: ^7.0.0

dependency_overrides:
  pubspec_deps_sorter:
    git:
      url: https://github.com/mrverdant13/altoke_bricks.git
      ref: e6a7e277975644de99187a86554345d96dc3a5b6
      path: ./tools/pubspec_deps_sorter/
  shell:
    git:
      url: https://github.com/mrverdant13/altoke_bricks.git
      ref: e6a7e277975644de99187a86554345d96dc3a5b6
      path: ./tools/shell/
