name: altoke_reactive_caches_brick_hooks
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.6.1 <4.0.0"

dependencies:
  mason: ^0.1.0
  path: ^1.9.0
  pubspec_deps_sorter:
    git:
      url: https://github.com/mrverdant13/altoke_bricks.git
      ref: 575389c0d0d0752834361c4b4be6888ef4e32f83
      path: ./tools/pubspec_deps_sorter/
  pubspec_parse: ^1.5.0
  shell:
    git:
      url: https://github.com/mrverdant13/altoke_bricks.git
      ref: 575389c0d0d0752834361c4b4be6888ef4e32f83
      path: ./tools/shell/

dev_dependencies:
  very_good_analysis: ^7.0.0
