name: altoke_dart_package_brick_hooks
publish_to: none

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  mason: ^0.1.0-dev.52
  path: ^1.9.0
  shell: any

dev_dependencies:
  very_good_analysis: ^5.1.0

dependency_overrides:
  shell:
    git:
      url: https://github.com/mrverdant13/altoke_bricks.git
      ref: b071442ea80006c2b9de19c2f69fe36ee4b102ce
      path: ./tools/shell/
