name: altoke_dart_package_brick_hooks
publish_to: none

environment:
  sdk: ">=3.5.1 <4.0.0"

dependencies:
  mason: ^0.1.0
  path: ^1.9.0
  shell:
    path: ../../../../tools/shell

dev_dependencies:
  very_good_analysis: ^7.0.0

dependency_overrides:
  shell:
    git:
      url: https://github.com/mrverdant13/altoke_bricks.git
      ref: 4231e8477f74b3ff53e4b21c13000dabb16392d5
      path: ./tools/shell/
