name: altoke_dart_package_brick_hooks
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  mason: ^0.1.1
  path: ^1.9.1
  shell:
    git:
      url: https://github.com/mrverdant13/altoke_bricks.git
      ref: 575389c0d0d0752834361c4b4be6888ef4e32f83
      path: ./tools/shell/

dev_dependencies:
  very_good_analysis: ^8.0.0
