name: altoke_storage_e2e
publish_to: none

environment:
  sdk: ">=3.5.1 <4.0.0"

dev_dependencies:
  checked_yaml: ^2.0.3
  data_persistence_approach:
    path: ../../../tools/data_persistence_approach
  mason: ^0.1.0-dev.59
  meta: ^1.15.0
  mocktail: ^1.0.4
  monorepo_elements:
    path: ../../../tools/monorepo_elements
  path: ^1.9.0
  shell:
    path: ../../../tools/shell
  test: ^1.25.8
  very_good_analysis: ^6.0.0
