name: {{#use_hive}}hive_local_database{{/use_hive}}
description: A persistent local database built on top of Hive.
version: 0.0.1+1
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  common:
    path: ../../common/
  collection: ^1.19.0
  hive: ^2.2.3
  {{#preconditions_met}}local_database{{/preconditions_met}}:
    path: ../{{#preconditions_met}}local_database{{/preconditions_met}}/
  meta: ^1.15.0

dev_dependencies:
  test: ^1.25.14
  very_good_analysis: ^7.0.0
