name: {{objects.snakeCase()}}_hive_storage
description: A persistent storage for {{objects.titleCase()}} built on top of Hive.
version: 0.0.1+1
publish_to: none

environment:
  sdk: ">=3.5.1 <4.0.0"

dependencies:
  common:
    path: ../../common/
  {{objects.snakeCase()}}_storage:
    path: ../{{objects.snakeCase()}}_storage/
  {{object.snakeCase()}}:
    path: ../../{{object.snakeCase()}}/
  collection: ^1.18.0
  hive: ^2.2.3
  json_annotation: ^4.9.0
  meta: ^1.15.0

dev_dependencies:
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  test: ^1.25.8
  very_good_analysis: ^6.0.0
