name: altoke_dart_package
description: An altoke Dart package.
version: 0.0.1+1
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dev_dependencies:
  #*w 1v 2> w*#
  #{{#use_code_generation}}#
  build_runner: ^2.4.14
  #*w 1v 2> w*#
  #{{/use_code_generation}}#
  test: ^1.25.14
  very_good_analysis: ^7.0.0
