name: drift_local_database
description: A persistent local database built on top of Drift (SQLite).
version: 0.0.1+1
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  common:
    path: ../../common/
  collection: ^1.19.0
  drift: ^2.22.1
  local_database:
    path: ../local_database/
  meta: ^1.15.0

dev_dependencies:
  build_runner: ^2.4.14
  drift_dev: ^2.22.1
  test: ^1.25.14
  very_good_analysis: ^7.0.0
