name: {{#use_isar}}isar_local_database{{/use_isar}}
description: A persistent local database built on top of Isar.
version: 0.0.1+1
publish_to: none

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  common:
    path: ../../common/
  collection: ^1.19.1
  isar:
    hosted: https://pub.isar-community.dev/
    version: 3.1.8
  {{#requirements_met}}local_database{{/requirements_met}}:
    path: ../{{#requirements_met}}local_database{{/requirements_met}}/
  meta: ^1.16.0

dev_dependencies:
  build_runner: ^2.5.4
  isar_generator:
    # HACK: Using a forked version of isar_generator to avoid version conflicts with `source_gen` v2.
    git:
      url: https://github.com/mdddj/isar
      ref: v3
      path: packages/isar_generator/
  test: ^1.25.15
  very_good_analysis: ^9.0.0
