{{#use_code_generation}}targets:
  $default:
    builders:
      {{#use_dart_mappable}}dart_mappable_builder:
        generate_for:
          - lib/src/types/optional.dart
        options:
          generateMethods:
            - stringify{{/use_dart_mappable}}{{#use_freezed}}freezed:
        generate_for:
          - lib/src/types/optional.dart
        options:
          copy_with: false
          map: false
          when: false{{/use_freezed}}{{/use_code_generation}}
