name: altoke_entity_e2e
publish_to: none

environment:
  sdk: ">=3.4.4 <4.0.0"

dev_dependencies:
  checked_yaml: ^2.0.3
  mason: ^0.1.0-dev.52
  meta: ^1.12.0
  mocktail: ^1.0.3
  monorepo_elements: any
  path: ^1.9.0
  shell: any
  test: ^1.25.2
  value_equality_approach: any
  very_good_analysis: ^5.1.0
