name: altoke_entity_e2e
publish_to: none

environment:
  sdk: ">=3.5.1 <4.0.0"

dev_dependencies:
  checked_yaml: ^2.0.3
  mason: ^0.1.0
  meta: ^1.15.0
  mocktail: ^1.0.4
  monorepo_elements:
    path: ../../../tools/monorepo_elements
  path: ^1.9.0
  shell: any
  test: ^1.25.8
  value_equality_approach:
    path: ../../../tools/value_equality_approach
  very_good_analysis: ^7.0.0
