name: {{projectName.snakeCase()}}
description: An {{projectName.titleCase()}}.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=3.22.3 <4.0.0"

dependencies:
  {{#use_auto_route}}auto_route: ^8.0.3
  {{/use_auto_route}}flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  {{#use_go_router}}go_router: ^14.0.1
  {{/use_go_router}}intl: ^0.19.0
  riverpod_annotation: ^2.3.4

dev_dependencies:
  {{#use_auto_route}}auto_route_generator: ^8.0.0
  {{/use_auto_route}}build_runner: ^2.4.8
  custom_lint: ^0.6.2
  flutter_test:
    sdk: flutter
  {{#use_go_router}}go_router_builder: ^2.4.1
  {{/use_go_router}}meta: ^1.11.0
  mocktail: ^1.0.3
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9
  very_good_analysis: ^5.1.0

flutter:
  generate: true
  uses-material-design: true
