name: generate_templates

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - .github/workflows/generate_templates.yaml
      - bricks/**/brick-gen.json
      - bricks/**/reference/**
      - tools/brick_generator/**

jobs:
  identify-brick-scopes:
    name: Identify brick scopes
    runs-on: ubuntu-latest
    outputs:
      scopes: ${{ steps.identify-brick-scopes.outputs.scopes }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v5
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.35.2
      - name: Install melos
        run: dart pub global activate melos 7.0.0-dev.9
      - name: Initialize melos
        run: melos bs --category=scopes
      - name: Identify brick scopes
        id: identify-brick-scopes
        run: echo "scopes=$(melos list --category=scopes --json | tr -d '\n')" >> "$GITHUB_OUTPUT"
      - name: List identified scopes
        run: echo "${{ join(steps.identify-brick-scopes.outputs.scopes.*.name, ', ') }}"
  generate-templates:
    name: Generate templates for the identified scopes
    runs-on: ubuntu-latest
    needs: identify-brick-scopes
    strategy:
      matrix:
        scope: ${{fromJson(needs.identify-brick-scopes.outputs.scopes)}}
    steps:
      - name: Build brick scope name
        id: build-brick-scope-name
        run: echo "brick-scope-name=$(echo ${{ matrix.scope.name }})" >> "$GITHUB_OUTPUT"
      - name: Build brick name
        id: build-brick-name
        run: echo "brick-name=$(echo ${{ steps.build-brick-scope-name.outputs.brick-scope-name }} | sed 's/_brick_scope//g')" >> "$GITHUB_OUTPUT"
      - name: Build brick tag name
        id: build-brick-tag-name
        run: echo "brick-tag-name=$(echo ${{ steps.build-brick-name.outputs.brick-name }} | sed 's/_/-/g')" >> "$GITHUB_OUTPUT"
      - name: Check out repository
        uses: actions/checkout@v5
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.35.2
      - name: Install melos
        run: dart pub global activate melos 7.0.0-dev.9
      - name: Initialize brick generator
        run: melos bs --scope=brick_generator
      - name: Set brick scope as unique relevant packages
        run: echo "MELOS_PACKAGES=${{ steps.build-brick-scope-name.outputs.brick-scope-name }}" >> "$GITHUB_ENV"
      - name: Generate template
        run: melos run brick.gen
      - name: Create PR
        uses: peter-evans/create-pull-request@v7
        with:
          base: main
          add-paths: |
            ./bricks/${{ steps.build-brick-name.outputs.brick-name }}/brick/__brick__/**
          branch: chore/${{ steps.build-brick-tag-name.outputs.brick-tag-name }}/update-template
          commit-message: 'chore(b-${{ steps.build-brick-tag-name.outputs.brick-tag-name }}): update template'
          title: 'chore(b-${{ steps.build-brick-tag-name.outputs.brick-tag-name }}): update template'
          body: Update template.
          delete-branch: true
          author: Altoke Bot <altoke.bot@users.noreply.github.com>
          committer: Altoke Bot <altoke.bot@users.noreply.github.com>
          assignees: mrverdant13
          reviewers: mrverdant13
