name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v6.0.0
      with:
        configuration-path: .github/labeler.yaml
        sync-labels: true
